[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name="ggj"
version="0.0.1"
dependencies = [
"mypy==1.14.1",
"mypy-extensions==1.0.0",
"typing_extensions==4.12.2"
]
