from typing import Protocol

class GameObject(Protocol):
    def update(self) -> None: ...
    def draw(self) -> None: ...
    def get_pos(self) -> tuple[int, int]: ...
    """
    The 'z-index' is the priority in which the object is
    drawn when multiple objects are on the same tile.

    The lower the z-index the higher priority
    """
    def zindex(self) -> int: ...
